version: '3.7'

services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: heroku_wake_up
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    env_file:
      - .env
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  
  monitoring_db:
    image: mongo-express
    container_name: mongo-express-heroku_wake_up
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo_db:27017/
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root  

